import { SiteConfig } from "@/types";

export const siteConfig: SiteConfig = {
  name: "Shinomura Hayato",
  title: "Shinomura Hayato | Full Stack Developer",
  description: "Hey there! I'm Shinomura Hayato, a passionate Full Stack Developer who crafts elegant, high-performance, and user-centric applications. I specialize in building modern web applications and managing databases to deliver seamless user experiences.",
  origin: "https://brightlearn.onrender.com",
  keywords: [
    "Shinomura Hayato",
    "Full Stack Developer",
    "Web Development Expert",
    "Database Management Specialist",
    "Software Engineer",
    "Web Developer",
    "Engineering",
    "Development",
    "Shinomura Hayato portfolio",
    "Shinomura Hayato blog",
    "Shinomura Hayato projects",
    "Shinomura Hayato experience",
    "Shinomura Hayato education",
    "Shinomura Hayato skills",
    "Shinomura Hayato contact",
    "Shinomura Hayato CV",
    "React",
    "Next.js",
    "JavaScript",
    "TypeScript",
    "HTML",
    "CSS",
    "Bootstrap",
    "Node.js",
    "MySQL",
    "PostgreSQL",
    "Firebase",
    "Flask",
    "Render",
    "Docker",
    "Web Development",
    "UI/UX",
    "Responsive Design",
    "Web Performance",
    "Web Accessibility",
    "SEO",
    "Git",
    "GitHub",
    "REST API",
    "State Management",
    "Testing",
    "CI/CD",
    "Agile",
    "Scrum"
  ],
  og: "https://brightlearn.onrender.com/og.png",
  creator: {
    name: "Shinomura Hayato",
    url: "https://brightlearn.onrender.com",
  },
  socials: {
    github: "https://github.com/hayato-shino05",
    x: "https://x.com/hayato_shino05",
  },
  siteUrl: "https://brightlearn.onrender.com",
};